spring.application.name=crud

spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.config.import=file:.env[.properties]

# Paksa Hibernate menggunakan nama kolom persis sesuai variabel/anotasi @Column
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# Membantu melihat query SQL yang dijalankan di Console IntelliJ
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true